name: release
on:
  create:
    tags:
    - v*.*.*

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
      with:
          fetch-depth: 1
    - name: Setup Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Build
      run: |
        npm ci
        npm run build
        npm run release
    - name: Upload to release
      uses: Shopify/upload-to-release
      with:
        path: markRestIcon.zip
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        content-type: application/zip
    
