name: release
on:
  create:
    tags:
    - v*.*.*

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
      with:
          fetch-depth: 1
    - name: Setup Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    
